-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\chorus_try10sin\circular_buffer_delay1.vhd
-- Created: 2021-04-19 22:46:32
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: circular_buffer_delay1
-- Source Path: chorus_try10sin/dataplane/double_chorus/circular buffer delay1
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY circular_buffer_delay1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_2048_0                      :   IN    std_logic;
        signal_in                         :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
        delay                             :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        signal_out                        :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En23
        );
END circular_buffer_delay1;


ARCHITECTURE rtl OF circular_buffer_delay1 IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT DualRateDualPortRAM_generic
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          din_A                           :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          addr_A                          :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          we_A                            :   IN    std_logic;
          din_B                           :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          addr_B                          :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          we_B                            :   IN    std_logic;
          doutA                           :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          doutB                           :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
          );
  END COMPONENT;

  -- Component Configuration Statements
--   FOR ALL : DualRateDualPortRAM_generic
--     USE ENTITY work.DualRateDualPortRAM_generic(rtl);

  -- Signals
  SIGNAL signal_in_signed                 : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL signal_in_1                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL Counter_Free_Running_out1        : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL Counter_Free_Running_out1_1      : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL delay_unsigned                   : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL always_write_a_out1              : std_logic;
  SIGNAL Constant_out1                    : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL Subtract_sub_cast                : signed(14 DOWNTO 0);  -- sfix15
  SIGNAL Subtract_sub_cast_1              : signed(14 DOWNTO 0);  -- sfix15
  SIGNAL Subtract_sub_temp                : signed(14 DOWNTO 0);  -- sfix15
  SIGNAL Subtract_out1                    : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL always_read_b_out1               : std_logic;
  SIGNAL Dual_Rate_Dual_Port_RAM_out1     : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL Dual_Rate_Dual_Port_RAM_out2     : std_logic_vector(23 DOWNTO 0);  -- ufix24

BEGIN
  u_Dual_Rate_Dual_Port_RAM : DualRateDualPortRAM_generic
    GENERIC MAP( AddrWidth => 14,
                 DataWidth => 24
                 )
    PORT MAP( clk => clk,
              enb_1_2048_0 => enb_1_2048_0,
              din_A => std_logic_vector(signal_in_1),
              addr_A => std_logic_vector(Counter_Free_Running_out1_1),
              we_A => always_write_a_out1,
              din_B => std_logic_vector(Constant_out1),
              addr_B => std_logic_vector(Subtract_out1),
              we_B => always_read_b_out1,
              doutA => Dual_Rate_Dual_Port_RAM_out1,
              doutB => Dual_Rate_Dual_Port_RAM_out2
              );

  signal_in_signed <= signed(signal_in);

  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      signal_in_1 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2048_0 = '1' THEN
        signal_in_1 <= signal_in_signed;
      END IF;
    END IF;
  END PROCESS delayMatch1_process;


  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  Counter_Free_Running_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Counter_Free_Running_out1 <= to_unsigned(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2048_0 = '1' THEN
        Counter_Free_Running_out1 <= Counter_Free_Running_out1 + to_unsigned(16#0001#, 14);
      END IF;
    END IF;
  END PROCESS Counter_Free_Running_process;


  reduced_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Counter_Free_Running_out1_1 <= to_unsigned(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2048_0 = '1' THEN
        Counter_Free_Running_out1_1 <= Counter_Free_Running_out1;
      END IF;
    END IF;
  END PROCESS reduced_process;


  delay_unsigned <= unsigned(delay);

  always_write_a_out1 <= '1';

  Constant_out1 <= to_signed(16#000000#, 24);

  Subtract_sub_cast <= signed(resize(Counter_Free_Running_out1_1, 15));
  Subtract_sub_cast_1 <= signed(resize(delay_unsigned, 15));
  Subtract_sub_temp <= Subtract_sub_cast - Subtract_sub_cast_1;
  Subtract_out1 <= unsigned(Subtract_sub_temp(13 DOWNTO 0));

  always_read_b_out1 <= '0';

  signal_out <= Dual_Rate_Dual_Port_RAM_out2;

END rtl;

