-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\chorus_try10sin\NCO_HDL_Optimized2.vhd
-- Created: 2021-04-19 22:46:32
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: NCO_HDL_Optimized2
-- Source Path: chorus_try10sin/dataplane/double_chorus/NCO HDL Optimized2
-- Hierarchy Level: 2
-- 
-- NCO HDL Optimized
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY NCO_HDL_Optimized2 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_2048_0                      :   IN    std_logic;
        inc                               :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        validIn                           :   IN    std_logic;
        sine                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END NCO_HDL_Optimized2;


ARCHITECTURE rtl OF NCO_HDL_Optimized2 IS

  -- Component Declarations
  COMPONENT DitherGen_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          validIn                         :   IN    std_logic;
          dither                          :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
          );
  END COMPONENT;

  COMPONENT WaveformGen_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          phaseIdx                        :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12_E4
          sine                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
--   FOR ALL : DitherGen_block
--     USE ENTITY work.DitherGen_block(rtl);

--   FOR ALL : WaveformGen_block
--     USE ENTITY work.WaveformGen_block(rtl);

  -- Signals
  SIGNAL outsel_reg_reg                   : std_logic_vector(0 TO 4);  -- ufix1 [5]
  SIGNAL outsel                           : std_logic;
  SIGNAL const0                           : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL inc_unsigned                     : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL pInc                             : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL validPInc                        : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL accphase_reg                     : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL addpInc                          : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL pOffset                          : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL accoffset                        : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL accoffsete_reg                   : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL dither                           : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL dither_unsigned                  : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL casteddither                     : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL dither_reg                       : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL accumulator                      : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL accQuantized                     : unsigned(11 DOWNTO 0);  -- ufix12_E4
  SIGNAL outzero                          : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL outs                             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL outs_signed                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL validouts                        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL sine_tmp                         : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  u_dither_inst : DitherGen_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2048_0 => enb_1_2048_0,
              validIn => validIn,
              dither => dither  -- ufix4
              );

  u_Wave_inst : WaveformGen_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2048_0 => enb_1_2048_0,
              phaseIdx => std_logic_vector(accQuantized),  -- ufix12_E4
              sine => outs  -- sfix16_En14
              );

  outsel_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      outsel_reg_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2048_0 = '1' THEN
        outsel_reg_reg(0) <= validIn;
        outsel_reg_reg(1 TO 4) <= outsel_reg_reg(0 TO 3);
      END IF;
    END IF;
  END PROCESS outsel_reg_process;

  outsel <= outsel_reg_reg(4);

  -- Constant Zero
  const0 <= to_signed(16#0000#, 16);

  inc_unsigned <= unsigned(inc);

  pInc <= signed(resize(inc_unsigned, 16));

  
  validPInc <= const0 WHEN validIn = '0' ELSE
      pInc;

  -- Add phase increment
  addpInc <= accphase_reg + validPInc;

  -- Phase increment accumulator register
  AccPhaseRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      accphase_reg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2048_0 = '1' THEN
        accphase_reg <= addpInc;
      END IF;
    END IF;
  END PROCESS AccPhaseRegister_process;


  pOffset <= to_signed(16#0000#, 16);

  -- Add phase offset
  accoffset <= accphase_reg + pOffset;

  -- Phase offset accumulator register
  AccOffsetRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      accoffsete_reg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2048_0 = '1' THEN
        accoffsete_reg <= accoffset;
      END IF;
    END IF;
  END PROCESS AccOffsetRegister_process;


  dither_unsigned <= unsigned(dither);

  casteddither <= signed(resize(dither_unsigned, 16));

  -- Dither input register
  DitherRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dither_reg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2048_0 = '1' THEN
        dither_reg <= casteddither;
      END IF;
    END IF;
  END PROCESS DitherRegister_process;


  -- Add dither
  accumulator <= accoffsete_reg + dither_reg;

  -- Phase quantization
  accQuantized <= unsigned(accumulator(15 DOWNTO 4));

  outzero <= to_signed(16#0000#, 16);

  outs_signed <= signed(outs);

  
  validouts <= outzero WHEN outsel = '0' ELSE
      outs_signed;

  -- Output register
  OutputRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sine_tmp <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2048_0 = '1' THEN
        sine_tmp <= validouts;
      END IF;
    END IF;
  END PROCESS OutputRegister_process;


  sine <= std_logic_vector(sine_tmp);

END rtl;

